# Generated by Django 2.2.20 on 2021-05-24 08:45

from django.db import migrations


def fill_field_new_building(apps, schema_editor):
    construction_min_year = 2015
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=construction_min_year).update(new_building=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_field_new_building),
    ]