# Generated by Django 2.2.20 on 2021-05-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20210524_1922'),
    ]

    operations = []
