# Generated by Django 2.2.20 on 2021-05-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20210524_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='property_flats',
            field=models.ManyToManyField(related_name='flats_owner', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
