# Generated by Django 2.2.20 on 2021-05-25 13:26

from django.db import migrations


def fill_fiel_property_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        owner.property_flats.set(Flat.objects.filter(owner=owner.owner))


def move_backward(apps, schema_editor):
    return 0


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20210525_1626'),
    ]

    operations = [
        migrations.RunPython(fill_fiel_property_flats, move_backward)
    ]
